sub_filter_once off;
sub_filter_types text/html;

sub_filter 'https://github.com' '__HUB_URL__';
sub_filter 'https://raw.githubusercontent.com' '__RAW_URL__';
sub_filter 'https://gist.github.com' '__GIST_URL__';
sub_filter 'https://github.githubassets.com' '__ASSETS_URL__';
sub_filter 'https://codeload.github.com' '__ARCHIVE_URL__';
