sub_filter_once off;

sub_filter 'https://gist.github.com' '__GIST_URL__';
sub_filter 'https://gist.githubusercontent.com' '__GIST_URL__/gist-githubusercontent/';
sub_filter 'https://github.com' '__HUB_URL__';
sub_filter 'https://codeload.github.com' '__ARCHIVE_URL__';
