upstream github_raw_entry {
    server raw.githubusercontent.com:443;
    keepalive 32;
}

server {
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name __RAW_DOMAIN__;

    root /www/wwwroot/github-mirror/raw;
    index index.html;

    include snippets/tls-common.conf;
    include snippets/mirror-security.conf;
    include snippets/mirror-robots-deny.conf;

    access_log __LOG_DIR__/__RAW_DOMAIN__.access.log;
    error_log  __LOG_DIR__/__RAW_DOMAIN__.error.log warn;

    error_page 403 /errors/403-readonly.html;
    error_page 404 /errors/404.html;

    location = /errors/403-readonly.html {
        internal;
        alias __ERROR_ROOT__/403-readonly.html;
    }

    location = /errors/404.html {
        internal;
        alias __ERROR_ROOT__/404.html;
    }

    include snippets/mirror-readonly-methods.conf;
    include snippets/proxy-common.conf;

    location / {
        proxy_ssl_name raw.githubusercontent.com;
        proxy_pass https://github_raw_entry;
        proxy_set_header Host raw.githubusercontent.com;

        proxy_hide_header Set-Cookie;

        add_header X-Mirror-Raw "github-raw" always;
    }
}
