sub_filter_once off;

sub_filter 'https://gist.github.com' 'https://gist.github.example.com';
sub_filter 'https://gist.githubusercontent.com' 'https://gist.github.example.com/gist-githubusercontent/';
sub_filter 'https://github.com' 'https://github.example.com';
sub_filter 'https://codeload.github.com' 'https://archive.github.example.com';
