sub_filter_once off;

sub_filter 'https://github.com' 'https://github.example.com';
sub_filter 'https://raw.githubusercontent.com' 'https://raw.github.example.com';
sub_filter 'https://gist.github.com' 'https://gist.github.example.com';
sub_filter 'https://github.githubassets.com' 'https://assets.github.example.com';
sub_filter 'https://codeload.github.com' 'https://archive.github.example.com';
